turbonomic/prometurbo

prometurbo/pkg/discovery/constant/constants.go, prometurbo/pkg/discovery/discovery_client.go, prometurbo/pkg/discovery/discovery_client_test.go, prometurbo/pkg/discovery/dtofactory/entity_builder.go, prometurbo/pkg/discovery/exporter/metric_exporter.go, prometurbo/pkg/p8s_tap_service.go, prometurbo/pkg/registration/supply_chain_factory.go
- Add target validation so that validation fails if all exporters have no response.
- Add proxy entities for virtual applications so in the server side, the vApp commodities can be updated with usage values after stitching with the commodities from Kubeturbo.
=> Add target validation. Add proxy entities for virtual applications.

prometurbo/pkg/discovery/dtofactory/entity_builder.go
Prometurbo creates entities as proxy for stitching in server side. We don't want these proxy to participate in market analysis so they are flagged as not monitored.
=> Set proxy entities as not monitored

prometurbo/pkg/discovery/discovery_client.go, prometurbo/pkg/p8s_tap_service.go, prometurbo/pkg/registration/registration_client.go
Append a hash number from target name to target type to support adding multiple prometurbo targets.
=> Support adding multiple prometurbo targets

prometurbo/pkg/discovery/constant/constants.go, prometurbo/pkg/discovery/discovery_client_test.go, prometurbo/pkg/discovery/dtofactory/entity_builder.go
Remove capacity patching in proxy entities since prometurbo doesn't have information about capacities for transaction and response time.
=> Remove capacity patching in proxy entities

appmetric/pkg/addon/istio_metric.go, appmetric/pkg/inter/constants.go, appmetric/scripts/istio/ip.turbo.metric.yaml, prometurbo/pkg/discovery/dtofactory/entity_builder.go
- Change the istio-metric.yml to fetch the service namespace and name labels when executing the prometheus query for pod metrics.
- istio-metric parser will extract the lables
- entity dto builder uses the labels to contract the key for virtual application and application entities.
=> OM-46220 Change key for vapp and app entities using the service id

appmetric/pkg/addon/webdriver_metric.go
The default webdriver metrics are in seconds.  I added a multiplier in the query to make it return in milliseconds, which is what Turbo server expects.
=> Adjusting the webdriver query to be in milliseconds

prometurbo/pkg/discovery/constant/constants.go, prometurbo/pkg/discovery/discovery_client.go, prometurbo/pkg/discovery/dtofactory/entity_builder.go, prometurbo/pkg/registration/supply_chain_factory.go
This patch only includes the part at the probe side if the business app is populated from appMetric.
=> Allow creating businessApp when the relabel of business app is used at prometheus

appmetric/Makefile, appmetric/cmd/main.go, deploy/prometurbo_yamls/appmetric-config.yaml, deploy/prometurbo_yamls/prometurbo.yaml, prometurbo/Makefile
The PR:
* Supports reading the `appmetric` configuration from `configMap`
* Fixes a few issues in the deployment yaml
* Remove the `6.4dev` label in `Makefile`
I will submit a separate PR for the changes in helm charts, and also adding the operator.
=> Support appmetric configuration through configmap

prometurbo/pkg/p8s_tap_service.go
@esara I see that operator relevant changes are already introduced by [this commit](https://github.com/turbonomic/prometurbo/commit/d1a457eef5a7004ff19408bdab078d4fca1b5215).
Let me know if its desirable to update the sample yamls as listed [here](https://github.com/turbonomic/prometurbo/tree/master/deploy/prometurbo_yamls). Shouldn't a service account and a rolebinding yaml also be listed among the sample yamls?
I used the Makefile based build and `make product` failed `go vet` test for me. The other commit is a fix for that.
=> Read turbonomic credentials optionally from a secret

deploy/prometurbo-operator/helm-charts/prometurbo/templates/deployment.yaml, deploy/prometurbo/templates/deployment.yaml, deploy/prometurbo_yamls/prometurbo.yaml
helm install prometurbo prometurbo --namespace test --dry-run --debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: prometurbo
labels:
app.kubernetes.io/name: prometurbo
helm.sh/chart: prometurbo-0.1.0
app.kubernetes.io/instance: prometurbo
app.kubernetes.io/managed-by: Helm
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: prometurbo
app.kubernetes.io/instance: prometurbo
template:
metadata:
labels:
app.kubernetes.io/name: prometurbo
app.kubernetes.io/instance: prometurbo
spec:
containers:
- name: prometurbo
image: turbonomic/prometurbo:7.21.0
imagePullPolicy: IfNotPresent
args:
- --keepStandalone=false
- --createProxyVM=false
- --v=2
volumeMounts:
- name: prometurbo-config
mountPath: /etc/prometurbo
readOnly: true
- name: turbonomic-credentials-volume …
=> prometurbo configurable prometheus url for appmetric

go.mod, go.sum, pkg/config/prometheus-config.yaml, pkg/provider/provider.go, vendor/github.com/turbonomic/turbo-go-sdk/pkg/dataingestionframework/data/dif_metric.go, vendor/github.com/turbonomic/turbo-go-sdk/pkg/dataingestionframework/data/dif_types.go, vendor/modules.txt
This PR allows `prometurbo` to add key to application metrics. These keys are in the form of `namespace/service_name`. After stitching with applications and services from `kubeturbo`, theses applications and services will be participating in the same market for horizontal scale analysis.
=> Add key to commodities in Applications and Services

deploy/prometurbo-operator/deploy/operator.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/templates/configmap-prometurbo.yaml, deploy/prometurbo/templates/configmap-prometurbo.yaml, pkg/config/prometheus-config.yaml
This PR:
Add istio 1.5 exporter configuration to `prometurbo`.
Istio 1.5 used [Telemetry V2](https://istio.io/docs/reference/config/telemetry/metrics/), and the default standard metrics already meets our requirement, so there is no need for custom metrics any more.
=> Add istio 1.5 exporter configuration

deploy/prometurbo-operator/helm-charts/prometurbo/templates/configmap-prometurbo.yaml, deploy/prometurbo/templates/configmap-prometurbo.yaml, pkg/config/prometheus-config.yaml, pkg/provider/provider.go, pkg/topology/topology.go
This PR addresses a few issues related to Target turbo with turbo use case:
* [OM-58801](https://vmturbo.atlassian.net/browse/OM-58801): Use configured display name for business transactions.
* [OM-59080](https://vmturbo.atlassian.net/browse/OM-59080): Do not send business transactions that are not specified in topology configuration.
* [OM-58843](https://vmturbo.atlassian.net/browse/OM-58843): Set the time range of prometheus query range vector to 10 min to be consistent with the default discovery interval.
* Modify the query for garbage collection time to compute the value as the **percentage** of time spent on garbage collection during the past 10 min.
* Remove the query for JVM THREAD, as it is not the exact metric we are looking for. We want to get the thread count in a threadpool …
=> Fix miscellaneous issues related to target turbo with turbo

cmd/prometurbo.go, pkg/provider/provider.go, pkg/provider/task.go, pkg/server/server.go, pkg/worker/collector.go, pkg/worker/dispatcher.go, pkg/worker/worker.go
This PR implements support for concurrent discovery of metrics via goroutine. 
By nature of the entity definitions in `prometheus-config.yaml`, the queries to the Prometheus server can be parallelized based on prometheus URL, exporter and entity definition combination. For example, the following queries are independent of each other, and can be made in parallel:
```
- http://prometheus-server.turbonomic:9090, turbonomic, businessTransaction-http
- http://prometheus-server.turbonomic:9090, turbonomic, businessTransaction-grpc
- http://prometheus-server.turbonomic:9090, turbonomic, application
- http://prometheus-server.turbonomic:9090, turbonomic, databaseServer
- http://prometheus.istio-system:9090, istio, application
```
This PR creates a worker pool (default 4 workers) to process …
=> Concurrent discovery

.travis.yml, deploy/prometurbo-operator/deploy/crds/charts.helm.k8s.io_v1alpha1_prometurbo_cr.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/templates/configmap-prometurbo.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/values.yaml, deploy/prometurbo/templates/configmap-prometurbo.yaml, deploy/prometurbo_yamls/configmap-prometurbo.yaml
This PR makes the following changes:
* Update `istio` query
* Combine queries of different request protocols into one (`request_protocol=~".*"`)
* Aggregate queries with `sum by (instance,destination_service_namespace,destination_service_name,pod_name)`, so we can aggregate traffic with different security policies, and different response_code for the same pod. The pod_name label is reserved for improvement [OM-68744](https://vmturbo.atlassian.net/browse/OM-68744)
* Update `jmx-tomcat` query:
* Use `rate()` instead of `delta()/timeframe` to handle counter reset, based on @chlam4 's comment
* Remove `turbonomic` query:
* These are not needed for standalone `prometurbo`, and will only cause maintenance overhead
* Turbonomic query is packaged in prometurbo subchart in xl operator, which can …
=> Update istio query

deploy/prometurbo-operator/deploy/crds/charts.helm.k8s.io_v1alpha1_prometurbo_cr.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/templates/deployment.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/values.yaml, deploy/prometurbo/templates/deployment.yaml, deploy/prometurbo/values.yaml
This PR adds `ignoreCommodityIfPresent` command line option to:
*  Prometurbo operator deployment
*  Prometurbo helm deployment
For example:
```yaml
args:
logginglevel: 2
ignoreCommodityIfPresent: true
```
=> Add ignoreCommodityIfPresent to prometurbo operator and helm deployment

.travis.yml
Update go version to `1.17.6` to fix security vulnerability:
CVE | Severity | Fixed GO version
-- | -- | --
2021-38297 | Critical | 1.17.2, 1.16.9
2021-44716 | High | 1.17.5, 1.16.12
2021-41772 | High | 1.17.3, 1.16.10
2021-41771 | High | 1.17.3, 1.16.10
2021-39293 | High | 1.17.1, 1.16.8
=> Update go version to 1.17.6 in travis

pkg/config/prometheus-config.yaml
Fix the unit inconsistency for node exporter memory used
=> [OM-75737]: Fix the unit inconsistency for node exporter memory used

deploy/prometurbo-operator/helm-charts/prometurbo/templates/configmap-prometurbo.yaml, deploy/prometurbo/templates/configmap-prometurbo.yaml, deploy/prometurbo_yamls/configmap-prometurbo.yaml
Fix the unit scale for the node memory query to fix extremely high utilization values when Prometurbo data is stitched.
When Prometurbo is running in a stitched environment with the node exporter running, we've received reports of extremely high utilization values. These appear to be the result of the units in the node query being off.
Prometurbo registers with the _Custom_ probe category, while Kubeturbo registers with the _Cloud Native_ category. During the stitching phase, probes with the _Custom_ category stitch last, which results in the Prometurbo data being retained. Since the scale of the query result is off, we see extremely high utilization when this happens.
We fixed once instance of this in a [previous PR](https://github.com/turbonomic/prometurbo/pull/76/files), but must've …
=> [OM-88664]: Fixed scale for node memory query.

.travis.yml, Makefile, build/Dockerfile
This PR supports building a multi-arch manifest images of prometurbo that has multiple images supporting different architectures
**Changes:**
1. Update the product target in the Makefile to produce binaries that supports linux/amd64, linux/arm64, linux/ppc64le and linux/s390x OS/Arch combinations respectively.
- Add buildkit flag to ensure builds without buildx pre-installed
2. Update the Dockerfile to copy appropriate binary using the built-in TARGETPLATFORM environment variable supported by docker build
3. Update .travis.yml to build docker image with master branch and release tag builds
- Install docker buildx plugin. 
- Create a new buildx instance, build and push the image
**Test**
- Building multi-arch manifest images of prometurbo
Creating prometurbo community operator in OCP on …
=> [OM-91935 ]Multiarch docker image support changes

deploy/prometurbo-operator/Dockerfile
Intent
Remediate the vulnerability in prometurbo-operator that was reported by synk scan related to libksba package in RH OS
Background
With the current prometurbo-operator base image v1.22, there was a critical vulnerability on libska package that was reported by synk scan. This vulnerability was fixed under the operator-framework/helm-operator with version 1.25
Testing
Run docker scan on the local image that was created with prometurbo-operator image version of 1.25, this change has remediated the critical vulnerability that was reported earlier by synk
=> [OM-92467]: update prometurbo-operator base image to v1.25

build/Dockerfile, deploy/prometurbo-operator/Dockerfile, deploy/prometurbo-operator/Makefile
This PR fixes [CVE-2022-42898](https://access.redhat.com/security/cve/CVE-2022-42898) by:
* Updating `krb5-libs` in `prometurbo`  image
* Updating `krb5-libs` in `prometurbo-operator` image
This PR also updates MAINTAINER and removes outdated labels.
=> [OM-93683] Fix security vulnerability CVE-2022-42898

deploy/README.md, deploy/prometurbo-operator/deploy/crds/charts.helm.k8s.io_prometurbos_crd.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/templates/deployment.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/values.yaml, deploy/prometurbo/templates/deployment.yaml, deploy/prometurbo/values.yaml, deploy/prometurbo_yamls/deployment.yaml
update prometurbo yaml to pull image from icr.io.
➜  ~ skopeo list-tags docker://icr.io/cpopen/turbonomic/turbodif
{
"Repository": "icr.io/cpopen/turbonomic/turbodif",
"Tags": [
"8.6.3",
"8.6.4",
"8.6.5",
"8.6.6",
"8.7.0",
"8.7.1",
"8.7.2-SNAPSHOT",
"8.7.2",
"8.7.3-SNAPSHOT",
"8.7.3",
"8.7.4-SNAPSHOT"
]
}
➜  ~ skopeo list-tags docker://icr.io/cpopen/turbonomic/prometurbo
{
"Repository": "icr.io/cpopen/turbonomic/prometurbo",
"Tags": [
"8.6.3",
"8.6.4",
"8.6.5",
"8.6.6",
"8.7.0",
"8.7.1",
"8.7.2-SNAPSHOT",
"8.7.2",
"8.7.3-SNAPSHOT",
"8.7.3",
"8.7.4-SNAPSHOT"
]
}
=> [OM-93337]: update prometurbo yaml to pull image from icr.io

deploy/prometurbo-operator/Dockerfile, deploy/prometurbo-operator/Makefile, deploy/prometurbo-operator/helm-charts/prometurbo/templates/deployment.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/values.yaml, deploy/prometurbo/templates/deployment.yaml
After switching to `kubeturbo` image registry to `icr.io`, user cannot change the `prometurbo` and `turbodif` version using the `icr.io/cpopen/turbonomic` repository. This is a critical issue as user cannot change version to match with old server version.
* Remove the logic to set hardcoded image digest for `prometurbo` and `turbodif` images
* Allow build script to set default `prometurboTag` and `turbodifTag` in `values.yaml`
With the above changes, the build script should specify a `VERSION` build argument when building `prometurbo-operator` container image, for example:
```
docker buildx build --platform "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x" --build-arg VERSION=8.8.0 --push -t icr.io/cpopen/turbonomic/prometurbo-operator:8.8.0 .
```
The `Dockerfile` will replace the …
=> [OM-95987] Allow changing image tag with certified prometurbo-operator

.gitignore, deploy/prometurbo-operator/helm-charts/prometurbo/templates/serviceaccount.yaml, deploy/prometurbo/templates/serviceaccount.yaml
Due to an error in .gitignore, the new `serviceaccount.yaml` file were not pushed. This PR addresses the issue.
=> [OM-98404] Add missing serviceaccount file to prometurbo deployment

Makefile, build/Dockerfile.multi-archs, go.mod
Please refer to the PR: https://github.com/turbonomic/kubeturbo/pull/838
Please refer to the PR: https://github.com/turbonomic/kubeturbo/pull/838
Please refer to the PR: https://github.com/turbonomic/kubeturbo/pull/838
1. Run the command `make docker-buildx` to build multi-arch images and push it to docker(or icr)
Could see `prometurbo` image is built and pushed to docker with multi-archs
3. Scan the image with `twistlock`
The report doesn't have any CVE issue on Go
[twistlock-scan-results-20230406-185150-N-UTC-EE766333.results.csv](https://github.com/turbonomic/prometurbo/files/11173678/twistlock-scan-results-20230406-185150-N-UTC-EE766333.results.csv)
5. Deploy the image in a K8s cluster and check if the pod can run 
The pod could run with the new image and there is  no outstanding …
=> [OM-99776]:Support multi-stage build and update GO to 1.20

Makefile, pkg/provider/customresource/provider.go, pkg/provider/task.go, pkg/provider/task_test.go, pkg/topology/topology.go
Today we use `<IP>-<First Segment Of Cluster ID>` as the matching attribute of an entity. This is likely to be risky as there is still a possibility for collision. We have decided to use the `<IP>-<Full Cluster ID>` instead such that there the chance for collision will be practically zero.
As a part of the changes, we also make the entity ID unique by appending the cluster ID.
We only append Cluster ID to matching attribute and entity ID when the application is hosted on container.
I have decided not to hash the string because:
* The length of a typical MD5 or SHA256 hash range from 32 - 64 characters, which doesn't really save much space
* It becomes difficult to debug when there is a problem with stitching when the value is hashed
Sample output from `prometurbo` where `uniqueId` and …
=> [OM-100448] Use the entire cluster svc ID as the unique identifier

deploy/prometurbo-operator/deploy/crds/charts.helm.k8s.io_v1_prometurbo_cr.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/templates/serviceaccount.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/values.yaml, deploy/prometurbo/templates/serviceaccount.yaml, deploy/prometurbo/values.yaml
**Intent**
We want to setup multiple Prometurbo probes for the same k8s cluster.
**Problem** 
When creating the second Prometurbo probe, we get the error that ClusterRoleBinding already exists.
**Solution**
Make ClusterRoleBinding unique based on the Prometurbo name and the namespace.
In addition, Eva insisted that we should not use the default targetName when creating Prometurbo instance.
**Testing**
Tested for two type of Prometurbo deployments:
- via Helm Charts
- via Operator
For each method, I created two Prometurbos. I saw no errors in Prometurbo Operator log.
=> [TRB-40754]: Unique ClusterRoleBinding name

deploy/prometurbo-operator/deploy/operator.yaml, deploy/prometurbo-operator/helm-charts/prometurbo/templates/serviceaccount.yaml, deploy/prometurbo/templates/serviceaccount.yaml, deploy/prometurbo/values.yaml
**Intent**
We want to run multiple Prometurbos on the same cluster.
**Fix**
ClusteRole and ClusterRoleBinding are cluster-wide resources. Their names need to be unique. ServiceAccount is namespaced and does not need to be unique.
=> [TRB-40754]: Unique ClusterRoleBinding name 2

.travis.yml, build/Dockerfile.multi-archs
- Upgrade go version to 1.20.5 to solve the [CVE issue](https://jsw.ibm.com/browse/TRB-42881)
Build dev image with the changes and scan it with twistlock, vulnerability issue resolved
`./tt images pull-and-scan --user xxxxx --url "https://w3twistlock.sos.ibm.com" --control-group public docker.io/sumanthkodali/turbodif-cve:latest`
[twistlock-scan-results-20230703-184344-N-UTC-E53B3D54.results.csv](https://github.com/turbonomic/prometurbo/files/11940189/twistlock-scan-results-20230703-184344-N-UTC-E53B3D54.results.csv)
=> [TRB-42880]: Upgrade go version to 1.20.5 to fix cve-2023-29404

deploy/prometurbo-operator/Makefile
This PR is an enhancement to the already merged PR - https://github.com/turbonomic/prometurbo/pull/108
This PR has a few enhancements from the previous [one](https://github.com/turbonomic/prometurbo/pull/108)
**Note:**
- The `OPERATOR_BETA_RELEASE_MINOR_VERSION` parameter is no longer necessary and has been eliminated, as the recipe itself can now determine the minor version by querying the repository.
- The `beta` release channel will **always** have the `SNAPSHOT` version of the image.
- The `stable` release channel will **always** have the `non-SNAPSHOT` version of the image.
**Enhancements are as follows**
- Now, utilizing GitHub API, this recipe is capable of querying the turbodeploy GitHub repository to examine the release versions for both the stable and beta channels.
- In the …
=> [TRB-45491] Prometurbo certified operator bundle automation enhancement

deploy/prometurbo-operator/Makefile, deploy/prometurbo-operator/bundle-template/cluster_permissions_automation.py
https://jsw.ibm.com/browse/TRB-46035
**Prometurbo Certified Operator Automation Bug**
Issue with Updating olm.skipRange in Makefile Rule and ruamel version creating spacing issues when modifying csv
- **Incorrect Pipe Handling**: In the original Makefile rule, the pipe (|) used for chaining yq commands wasn't properly escaped. This was caught only when running the script through Jenkins
- Ruamel.yaml version 0.17.32 is introducing extra spacing when replacing lengthy lines, hence opting to change to version 0.16.12, which maintains the original indentation for lengthy lines when updating csv
**Solution:**
- separated the computations for olm.skipRange values. The eval function was used to define OLMSKIP_LOWER_BOUND and OLMSKIP_UPPER_BOUND variables ahead of the main command.
- single, yq …
=> [TRB-46035] bug fix changes to eliminate piping issue and space issue due to ruamel version

.travis.yml, build/Dockerfile.multi-archs
Intent
Upgrade go version
to fix [CVE-2023-39533](https://cve.circl.lu/cve/CVE-2023-39533)
Testing
Build dev image with the changes and scan it with twistlock, vulnerability issue resolved
[twistlock-scan-results-20230825-033603-259610000-UTC-1247E771.results.csv](https://github.com/turbonomic/prometurbo/files/12435354/twistlock-scan-results-20230825-033603-259610000-UTC-1247E771.results.csv)
=>  [TRB-46400]: Upgrade go version to 1.20.7 to fix CVE-2023-39533

.travis.yml
Remove coveralls integrations from Travis builds.
Coveralls is free for public repositories, but requires licenses for private/enterprise repos. Since we are moving to IBM enterprise Git, we need to remove this integration. We should be able to capture code coverage using SonarQube, or some other approved, tool in the future. 
N/A - will test enterprise build after merging.
=> [TRB-46808]: Removed coveralls integration from travis build.
